export const AuthActionTypes = {
  RES_SUCCESS: 'RES_SUCCESS',
  RES_ERROR: 'RES_ERROR',
  LOGIN_USER: 'LOGIN_USER',
  REGISTER_USER: 'REGISTER_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  RESET_STATE: 'RESET_STATE',
}
