export const AuthActionTypes = {
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_ERROR: 'AUTH_ERROR',
  LOGIN_USER: 'LOGIN_USER',
  REGISTER_USER: 'REGISTER_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  RESET_STATE: 'RESET_STATE',
}
