export const ChannelActionTypes = {
  SET_CURRENT_CHANNEL: 'SET_CURRENT_CHANNEL',
  SET_CHANNELS: 'SET_CHANNELS',
  LOAD_CHANNELS: 'LOAD_CHANNELS',
  CREATE_CHANNEL: 'CREATE_CHANNEL',
  RES_SUCCESS: 'RES_SUCCESS',
  RES_ERROR: 'RES_ERROR',
  RESET_STATE: 'RESET_STATE'
};
