export const ProfileActionTypes = {
  SET_USER: 'SET_USER', // ONLY SET USER ON CLIENT SIDE
  UPDATE_USER: 'UPDATE_USER', // UPDATES USER ON SERVER AND CLIENT
  RES_SUCCESS: 'RES_SUCCESS',
  RES_ERROR: 'RES_ERROR',
  RESET_STATE: 'RESET_STATE',
  RESET_REST_STATE: 'RESET_REST_STATE'
}
